#![no_main]
use libfuzzer_sys::fuzz_target;

fuzz_target!(|data: (&TargetConfig, bool)| {
    // Automatically generated by CovOpt-Analyzer
    let _ = crate::entropy::calculate_entropy_score(data.0, data.1);
});
