#![no_main]
use libfuzzer_sys::fuzz_target;

fuzz_target!(|data: (&str, &str, bool)| {
    // Automatically generated by CovOpt-Analyzer
    let _ = crate::harden::run_sanitizer(data.0, data.1, data.2);
});
