#![no_main]
use libfuzzer_sys::fuzz_target;

fuzz_target!(|data: (&Path, usize)| {
    // Automatically generated by CovOpt-Analyzer
    let _ = crate::static_analysis::analyze_variables(data.0, data.1);
});
