#![no_main]
use libfuzzer_sys::fuzz_target;

fuzz_target!(|data: (&str, &str, &str, f64)| {
    // Automatically generated by CovOpt-Analyzer
    let _ = crate::explore::run(data.0, data.1, data.2, data.3);
});
