#![no_main]
use libfuzzer_sys::fuzz_target;

fuzz_target!(|data: (Option<&str>, Option<&str>, &str)| {
    // Automatically generated by CovOpt-Analyzer
    let _ = crate::profiler::run_profile(data.0, data.1, data.2);
});
